### ISSUE TITLE
missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [thepurpleblob/moodle-tool_environment#1]
PHPLucidFrame\Console needs to be referenced in a thirdpartylibs.xml file within the root of the plugin. This will allow you to specifiy it uses the MIT license but will also make cibot ignore the file.

**Comment by thepurpleblob** [comment]
Oooh.... didn't know anything about that. I'll get onto it!

**Comment by thepurpleblob** [comment]
Sorted (hopefully)

Thanks for the 'heads up' Dan
