### ISSUE TITLE
The English language strings are not available in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [thepurpleblob/moodle-tool_environment#2]
I found it odd that the English language strings are not available in AMOS for translation (https://lang.moodle.org/local/amos/view.php?v=3600&t=1544975878&l=es_mx&c=tool_environment).

I did not see any of the common causes for this condition (https://docs.moodle.org/dev/Translating_plugins#Non-translatable_strings).

**Comment by thepurpleblob** [comment]
I haven't a clue how AMOS works... I assume it should...

**Comment by germanvaleroelizondo** [comment]
This plugin is not in the 'Other' category (https://docs.moodle.org/dev/Translating_plugins#Plugins_in_the_Other_category) that do not have English language strings in AMOS.
 
Maybe you can contact David Mudrak and ask him about this ?

**Comment by thepurpleblob** [comment]
Sorry - I'm not being much use here. I created an AMOS account and had a look. I think I agree although I find the UI confusing. 

I posted a question here, https://moodle.org/mod/forum/discuss.php?d=380384 . If I have missed anything you may wish to add the information there.

Thanks for your interest by the way. I'm struggling a bit as I seem to have managed to avoid any involvement in translated strings before now.

**Comment by germanvaleroelizondo** [comment]
Issue fixed by David Mudrak as per https://moodle.org/mod/forum/discuss.php?d=380384
